In [1]:
#1. Given the following 2D array array_2d, how can you access the element at the second row and third column?

import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

element = array_2d[1, 2]

print("Element at the second row and third column:", element)


Element at the second row and third column: 6


In [2]:
# 2. Given the following 2D array array_2d, how can you access the element at the first row and third column?

import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = array_2d[0, 2]

print("Element at the first row and third column:", element)


Element at the first row and third column: 3


In [3]:
# 3. Using indexing, how can you extract the first row of array_2d?

import numpy as np


array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

first_row = array_2d[0, :]

print("First row:", first_row)


First row: [1 2 3]


In [4]:
# 4. How can you access the second column of array_2d?

import numpy as np


array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
second_column = array_2d[:, 1]


print("Second column:", second_column)


Second column: [2 5 8]


In [5]:
# 5. Given array_2d, how can you create a new array containing only the elements that are greater than 4

import numpy as np


array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


filtered_array = array_2d[array_2d > 4]

print("Original 2D Array:")
print(array_2d)
print("New array with elements greater than 4:")
print(filtered_array)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
New array with elements greater than 4:
[5 6 7 8 9]
