In [8]:
 # 1) Generate a 3x3 matrix of random values between 0 and 1. What is the average of all the elements?
    
import numpy as np


random_matrix = np.random.rand(3, 3)
average = np.mean(random_matrix)


print("Random Matrix:")
print(random_matrix)
print("Average of all elements:", average)


Random Matrix:
[[0.93214489 0.22992408 0.99657509]
 [0.80279913 0.51857603 0.3940059 ]
 [0.05683522 0.88590171 0.18406017]]
Average of all elements: 0.5556469118910168


In [7]:
# 2) Generate a 2x8 matrix of random values. What is the maximum value among all the elements?

import numpy as np

random_matrix = np.random.rand(2, 8)

max_value = np.max(random_matrix)


print("Random Matrix:")
print(random_matrix)
print("Maximum value among all elements:", max_value)


Random Matrix:
[[0.68977739 0.9661985  0.94842937 0.42406251 0.63202897 0.84450813
  0.87681569 0.21904601]
 [0.92233152 0.61772179 0.93946285 0.12048319 0.55925627 0.26711407
  0.53225489 0.04478797]]
Maximum value among all elements: 0.9661984954830823


In [6]:
# 3) Generate a 4x4 matrix of random values from a standard normal distribution. What is the mean of all the elements?`

import numpy as np


random_matrix = np.random.randn(4, 4)

mean_value = np.mean(random_matrix)

print("Random Matrix from Standard Normal Distribution:")
print(random_matrix)
print("Mean of all elements:", mean_value)


Random Matrix from Standard Normal Distribution:
[[-1.18495466  1.23295208  0.16677616  1.10216708]
 [ 0.63075103 -0.01820137  0.95282091 -0.59199962]
 [ 0.28279518  0.90198171 -1.16595391 -0.06179812]
 [ 1.07628304 -0.32715052 -2.42667726 -0.38079082]]
Mean of all elements: 0.011812556372175972


In [9]:
# 4) Create a 4x5 matrix of random integers between -100 and 100. What is the sum of the elements in the third column?

import numpy as np


random_matrix = np.random.randint(-100, 101, size=(4, 5))

sum_third_column = np.sum(random_matrix[:, 2])


print(" Random Integer Matrix:")
print(random_matrix)
print("Sum of elements in the third column:", sum_third_column)


 Random Integer Matrix:
[[ 23 -81 -65 -16 -30]
 [ 72 -84  11  20  -9]
 [  8  52  21 -85  14]
 [ 90 -31  18  24 -55]]
Sum of elements in the third column: -15


In [10]:
# 5) Create a 1D array of numbers from 1 to 12. Reshape it into a 3x4 matrix. What is the sum of all the elements in the matrix?

import numpy as np


array_1d = np.arange(1, 13)

matrix_3x4 = array_1d.reshape(3, 4)

sum_of_elements = np.sum(matrix_3x4)

print("1D Array:")
print(array_1d)
print("Reshaped 3x4 Matrix:")
print(matrix_3x4)
print("Sum of all elements in the matrix:", sum_of_elements)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 3x4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sum of all elements in the matrix: 78


In [11]:
# 6) 6)	Create a 2D array with dimensions 4x6. What is the shape of the array?

import numpy as np

array_2d = np.zeros((4, 6))

print("2D Array:")
print(array_2d)
print("Shape of the array:", array_2d.shape)


2D Array:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Shape of the array: (4, 6)


In [12]:
# 7) 7)	Generate a 1D array with 15 elements. Reshape it into a 3x5 matrix. What is the new shape of the matrix?

import numpy as np


array_1d = np.arange(1, 16)


matrix_3x5 = array_1d.reshape(3, 5)

print("1D Array:")
print(array_1d)
print("Reshaped 3x5 Matrix:")
print(matrix_3x5)
print("New shape of the matrix:", matrix_3x5.shape)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped 3x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
New shape of the matrix: (3, 5)
