In [1]:
import numpy as np

In [2]:
# 1) How can I create a NumPy array by converting a Python list into an array? my_list = [1, 2, 3, 4, 5]


my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [7]:
# 2) Can I create a 2D NumPy array from a list of lists?


arr_2d = np.array(my_list)
arr_2d



array([1, 2, 3, 4, 5])

In [20]:
# 3) How do I create a reversed array of even integers using numpy.arange()? 

even_integers = np.arange(2, 21, 2) 
reversed_even_integers = even_integers[::-1]

In [21]:
reversed_even_integers

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [18]:
# 4) How can I create an array with decreasing values using numpy.arange()?


decreasing_array = np.arange(10, 0, -1)

In [19]:
decreasing_array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [31]:
# 5) Generate an array of 7 numbers equally spaced between -2 and 2. What is the sum of their squares?


import numpy as np


numbers = np.linspace(-2, 2, 7)
sum_of_squares = np.sum(numbers**2)


print("Array:", numbers)
print("Sum of squares:", sum_of_squares)

Array: [-2.         -1.33333333 -0.66666667  0.          0.66666667  1.33333333
  2.        ]
Sum of squares: 12.444444444444445


In [32]:
# 6)	Create an array containing 12 numbers that are evenly spaced between 10 and 20. What is the average of these numbers?

import numpy as np


numbers = np.linspace(10, 20, 12)
average = np.mean(numbers)


print("Array:", numbers)
print("Average:", average)


Array: [10.         10.90909091 11.81818182 12.72727273 13.63636364 14.54545455
 15.45454545 16.36363636 17.27272727 18.18181818 19.09090909 20.        ]
Average: 15.0


In [36]:
# 1) Create a 3x3 identity matrix and multiply it by a vector [2, 3, 4]. What is the result?

import numpy as np


identity_matrix = np.eye(3)
vector = np.array([2, 3, 4])

result = np.dot(identity_matrix, vector)


print("Identity Matrix:")
print(identity_matrix)


Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
vector

array([2, 3, 4])

In [40]:
result 

array([2., 3., 4.])